resource/views/region_views.py
from flask import Blueprint, url_for, render_template, flash, request
from werkzeug.utils import redirect
from resource.models import Region, Server
from resource.forms import DateForm
from datetime import datetime

bp = Blueprint('region', __name__, url_prefix='/region')


@bp.route('/<int:region_id>/', methods=["GET"])
def detail(region_id):
    regions = Region.query.all()
    region = Region.query.get_or_404(region_id)

    page = request.args.get('page', type=int, default=1)
    servers = Server.query.filter_by(region_id=region_id)
    servers = servers.paginate(page, per_page=10)

    form = DateForm()

    return render_template(
        'region/region_detail.html',
        regions=regions,
        region=region,
        servers=servers,
        form=form
    )


@bp.route('/<int:region_id>/usage', methods=["GET"])
def usage_detail(region_id):
    regions = Region.query.all()
    region = Region.query.get_or_404(region_id)

    page = request.args.get('page', type=int, default=1)
    servers = Server.query.filter_by(region_id=region_id)
    servers = servers.paginate(page, per_page=10)

    form = DateForm()

    date = request.args.get('date').split('-')
    record_date = datetime(int(date[0]), int(date[1]), int(date[2]), 0, 0)

    return render_template(
        'region/region_usage_detail.html',
        regions=regions,
        region=region,
        servers=servers,
        date=date,
        record_date=record_date,
        form=form
    )

resource/views/server_views.py
from flask import Blueprint, url_for, render_template, flash, request
from werkzeug.utils import redirect
from resource import db
from resource.models import Region, Server
from resource.forms import ServerForm

bp = Blueprint('server', __name__, url_prefix='/server')


@bp.route('create/region<int:region_id>/', methods=('GET', 'POST'))
def create(region_id):
    form = ServerForm()
    region = Region.query.get_or_404(region_id)

    if request.method == 'POST' and form.validate_on_submit():
        server = Server(region_id=region_id, host=form.host.data, cpu=form.cpu.data,
                        memory=form.memory.data, storage=form.storage.data)
        db.session.add(server)
        db.session.commit()
        return redirect(url_for('region.detail', region_id=region_id))

    return render_template('server/add_server.html', region=region, form=form)


@bp.route('update/<int:server_id>/', methods=('GET', 'POST'))
def update(server_id):
    form = ServerForm()
    server = Server.query.get_or_404(server_id)
    region_id = server.region_id

    if request.method == 'POST' and form.validate_on_submit():
        server.host = form.host.data
        server.cpu = form.cpu.data
        server.memory = form.memory.data
        server.storage = form.storage.data
        db.session.commit()
        return redirect(url_for('region.detail', region_id=region_id))

    return render_template('server/update_server.html', server=server, form=form)


@bp.route('delete/<int:server_id>/', methods=('GET', 'POST'))
def delete(server_id):
    server = Server.query.get_or_404(server_id)
    region_id = server.region_id

    if server:
        db.session.delete(server)
        db.session.commit()
    else:
        flash('server does not exist!')

    return redirect(url_for('region.detail', region_id=region_id))

resource/views/trend_views.py
from flask import Blueprint, render_template
from resource.models import Region
import pandas as pd
import json
import plotly
import plotly.express as px

bp = Blueprint('trend', __name__, url_prefix='/trend')


@bp.route('/<int:region_id>/', methods=["GET"])
def main(region_id):
    regions = Region.query.all()
    region = Region.query.get_or_404(region_id)

    line = {
        'cpu': json.dumps(get_cpu_usages_by_dates(region), cls=plotly.utils.PlotlyJSONEncoder),
        'memory': json.dumps(get_memory_usages_by_dates(region), cls=plotly.utils.PlotlyJSONEncoder),
        'storage': json.dumps(get_storage_usages_by_dates(region), cls=plotly.utils.PlotlyJSONEncoder)
    }

    return render_template('trend/trend.html', regions=regions, region=region, line=line)


def get_cpu_usages_by_dates(region):
    df = pd.DataFrame({
        'date': region.dates(),
        'usage': region.cpu_usage_by_date()
    })
    return px.line(df, x="date", y="usage", title=f"cpu usage trend in {region.name}")


def get_memory_usages_by_dates(region):
    df = pd.DataFrame({
        'date': region.dates(),
        'usage': region.memory_usage_by_date()
    })
    return px.line(df, x="date", y="usage", title=f"memory usage trend in {region.name}")


def get_storage_usages_by_dates(region):
    df = pd.DataFrame({
        'date': region.dates(),
        'usage': region.storage_usage_by_date()
    })
    return px.line(df, x="date", y="usage", title=f"storage usage trend in {region.name}")

resource/views/usage_views.py
from flask import Blueprint, url_for, render_template, flash, request
from werkzeug.utils import redirect
from resource import db
from resource.models import Region, Usage
from resource.forms import UsageForm
from datetime import datetime


bp = Blueprint('usage', __name__, url_prefix='/usage')


@bp.route('create/region<int:region_id>', methods=('GET', 'POST'))
def create(region_id):
    region = Region.query.get_or_404(region_id)
    servers = region.servers

    date = request.args.get('record_date')[:10].split('-')
    record_date = datetime(int(date[0]), int(date[1]), int(date[2]), 0, 0)

    form = UsageForm()

    if request.method == 'POST' and form.validate_on_submit():
        for server in servers:
            usage = Usage(
                server_id=server.id,
                cpu_usage=form.cpu_usage.data,
                memory_usage=form.memory_usage.data,
                storage_usage=form.storage_usage.data,
                record_date=record_date
            )
            db.session.add(usage)
        db.session.commit()

        return redirect(url_for('region.detail', region_id=region_id))

    return render_template('usage/add_usage.html', region=region, servers=servers, record_date=record_date, form=form, date=date)

resource/templates/region/add_server.html
<style>
    .modal-content {
        background-color:dimgrey
    }
</style>

<div class="modal fade" id="modal_add_server-{{ region.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add Server for {{ region.name }}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post" class="my-3">
            {{ form.csrf_token }}
          <div class="modal-body">
            <div class="mb-3">
              <label for="host" class="col-form-label">Host</label>
              <input type="text" class="form-control" id="host" name="host">
            </div>
            <div class="mb-3">
              <label for="cpu" class="col-form-label">CPU</label>
              <input type="text" class="form-control" id="cpu" name="cpu">
            </div>
            <div class="mb-3">
              <label for="memory" class="col-form-label">Memory</label>
              <input type="text" class="form-control" id="memory" name="memory">
            </div>
            <div class="mb-3">
              <label for="instance" class="col-form-label">Instance</label>
              <input type="text" class="form-control" id="instance" name="instance">
            </div>
          </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Confirm</button>
            </div>

            <!-- Error -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field, errors in form.errors.items() %}
                <strong>{{ form[field].label }}</strong>
                <ul>
                    {% for error in errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endfor %}
            </div>
            {% endif %}
        </form>
      </div>
    </div>
  </div>

resource/templates/region/region_detail.html
{% extends "base.html" %}

{% block title %}
{{ region.name }}
{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1>{{ region.name }}</h1>
    <form action="{{ url_for('region.usage_detail', region_id=region.id) }}" class="my-3">
        {{ form.csrf_token }}
        <label for="date">Select the record date:
          <input type="date" id="date" name="date" value="2022-01-01">
          <button type="submit" class="btn btn-outline-primary">Submit</button>
        </label>
        <a class="btn btn-outline-success" href="{{ url_for('trend.main', region_id=region.id) }}" role="button">Trend</a>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary" href="{{ url_for('server.create', region_id=region.id) }}" role="button">Add Server</a>
    </div>
    <table class="table table-hover table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Host</th>
            <th scope="col">CPU Total</th>
            <th scope="col">Memory Total</th>
            <th scope="col">Storage Total</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for server in servers.items %}
        <tr>
            <td>{{ ((servers.page-1) * servers.per_page) + loop.index }}</td>
            <td>{{ server.host }}</td>
            <td>{{ server.cpu }}</td>
            <td>{{ server.memory }}</td>
            <td>{{ server.storage }}</td>
            <td>
                <a class="btn btn-secondary" href="{{ url_for('server.update', server_id=server.id) }}" role="button">Update</a>
            </td>
            <td>
                {% include 'server/delete_server.html' %}
                <button class="btn btn-outline-danger" type="button" data-bs-toggle="modal" data-bs-target="#modal_delete_server-{{ server.id }}">Delete</button>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- Paginate -->
    <ul class="pagination justify-content-end">
        <!-- prev page -->
        {% if servers.has_prev %}
            <li class="page-item">
                <a class="page-link" href="?page={{ servers.prev_num }}">prev</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">Previous</a>
            </li>
        {% endif %}
        {% for page_num in servers.iter_pages() %}
            {% if page_num %}
                {% if page_num != servers.page %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="disabled">
                    <a class="page-link" href="javascript:void(0)">...</a>
                </li>
            {% endif %}
        {% endfor %}
        <!-- next page -->
        {% if servers.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ servers.next_num }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">Next</a>
            </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

resource/templates/region/region_usage_detail.html
{% extends "base.html" %}

{% block title %}
{{ region.name }} usage
{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1>{{ region.name }} usage in {{ date[0] }}-{{ date[1] }}-{{ date[2] }}</h1>
    <form action="{{ url_for('region.usage_detail', region_id=region.id) }}" class="my-3">
        {{ form.csrf_token }}
        <label for="date">Select the record date:
          <input type="date" id="date" name="date" value="2022-01-01">
          <button type="submit" class="btn btn-outline-primary">Submit</button>
        </label>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary" href="{{ url_for('usage.create', region_id=region.id, record_date=record_date) }}" role="button">Add Usage</a>
    </div>
    <table class="table table-hover table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Host</th>
            <th scope="col">CPU Usage</th>
            <th scope="col">CPU Total</th>
            <th scope="col">Memory Usage</th>
            <th scope="col">Memory Total</th>
            <th scope="col">Storage Usage</th>
            <th scope="col">Storage Total</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for server in servers.items %}
                {% for log in server.logs %}
                    {% if log.record_date == record_date %}
        <tr>
            <td>{{ ((servers.page-1) * servers.per_page) + loop.index }}</td>
            <td>{{ server.host }}</td>
            <td>{{ log.cpu_usage }}</td>
            <td>{{ server.cpu }}</td>
            <td>{{ log.memory_usage }}</td>
            <td>{{ server.memory }}</td>
            <td>{{ log.storage_usage }}</td>
            <td>{{ server.storage }}</td>
            <td>
                <a class="btn btn-secondary" href="{{ url_for('server.update', server_id=server.id) }}" role="button">Update</a>
            </td>
        </tr>
                {% endif %}
            {% endfor %}
        {% endfor %}
        </tbody>
    </table>

    <!-- Paginate -->
    <ul class="pagination justify-content-end">
        <!-- prev page -->
        {% if servers.has_prev %}
            <li class="page-item">
                <a class="page-link" href="?page={{ servers.prev_num }}">prev</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">Previous</a>
            </li>
        {% endif %}
        {% for page_num in servers.iter_pages() %}
            {% if page_num %}
                {% if page_num != servers.page %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="disabled">
                    <a class="page-link" href="javascript:void(0)">...</a>
                </li>
            {% endif %}
        {% endfor %}
        <!-- next page -->
        {% if servers.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ servers.next_num }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">Next</a>
            </li>
        {% endif %}
    </ul>
</div>
{% endblock %}