resource/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from resource import db
from resource.forms import UserCreateForm, UserLoginForm
from resource.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(name=form.name.data).first()
        if not user:
            user = User(name=form.name.data,
                        email=form.email.data,
                        password=generate_password_hash(form.password.data))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('User already exist.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(name=form.name.data).first()
        if not user:
            error = "User does not exist."
        elif not check_password_hash(user.password, form.password.data):
            error = "Password does not match."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

resource/views/region_views.py
from flask import Blueprint, url_for, render_template, flash, request
from werkzeug.utils import redirect
from resource.models import Region, Server
from resource.forms import DateForm
from datetime import datetime

bp = Blueprint('region', __name__, url_prefix='/region')


@bp.route('/<int:region_id>/', methods=["GET"])
def detail(region_id):
    regions = Region.query.all()
    region = Region.query.get_or_404(region_id)

    page = request.args.get('page', type=int, default=1)
    servers = Server.query.filter_by(region_id=region_id)
    servers = servers.paginate(page, per_page=10)

    form = DateForm()

    return render_template(
        'region/region_detail.html',
        regions=regions,
        region=region,
        servers=servers,
        form=form
    )


@bp.route('/<int:region_id>/usage', methods=["GET"])
def usage_detail(region_id):
    regions = Region.query.all()
    region = Region.query.get_or_404(region_id)

    page = request.args.get('page', type=int, default=1)
    servers = Server.query.filter_by(region_id=region_id)
    servers = servers.paginate(page, per_page=10)

    form = DateForm()

    date = request.args.get('date').split('-')
    record_date = datetime(int(date[0]), int(date[1]), int(date[2]), 0, 0)

    return render_template(
        'region/region_usage_detail.html',
        regions=regions,
        region=region,
        servers=servers,
        date=date,
        record_date=record_date,
        form=form
    )

resource/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title>
        {% block title %}
        Resource
        {% endblock %}
    </title>
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
    {% include "navbar.html" %}

    {% block content %}
    {% endblock %}
</body>
<style>
    body {
        background-color: #212121;
        color: white
    }
</style>
</html>

resource/templates/dashboard.html
{% extends "base.html" %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<div class="container">
    {% for region in regions %}
    <div class="row">
        <h2>{{ region.name }}</h2>
        <div class="col-6 col-md-4", id="{{ region.name }}-cpu">
        </div>
        <div class="col-6 col-md-4", id="{{ region.name }}-memory">
        </div>
        <div class="col-6 col-md-4", id="{{ region.name }}-storage">
        </div>
    </div>
    {% endfor %}
</div>


<!-- plotly CDN -->
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script>
    var id_list = [
        "east-cpu", "east-memory", "east-storage",
        "west-cpu", "west-memory", "west-storage",
        "south-cpu", "south-memory", "south-storage",
        "north-cpu", "north-memory", "north-storage"
    ]

    var graph = [
        {{ usage['east']['cpu'] | safe }}, {{ usage['east']['memory'] | safe }}, {{ usage['east']['storage'] | safe }},
        {{ usage['west']['cpu'] | safe }}, {{ usage['west']['memory'] | safe }}, {{ usage['west']['storage'] | safe }},
        {{ usage['south']['cpu'] | safe }}, {{ usage['south']['memory'] | safe }}, {{ usage['south']['storage'] | safe }},
        {{ usage['north']['cpu'] | safe }}, {{ usage['north']['memory'] | safe }}, {{ usage['north']['storage'] | safe }}
    ]

    for (i=0; i < id_list.length; i++) {
        Plotly.plot(id_list[i], graph[i], {})
    }
</script>
{% endblock %}

resource/templates/form_errors.html
<!-- field error -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash error -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

resource/templates/navbar.html
<!-- navigation bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Resource</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if g.user %}
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% for region in regions %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('region.detail', region_id=region.id) }}">{{ region.name }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
        <ul class="navbar-nav">
          <div class="nav-item">
            <a class="nav-link" href="#">{{ g.user.name }}</a>
          </div>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
         </ul>
      {% else %}
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.signup') }}">Signup</a>
            </li>
        </ul>
      {% endif %}
    </div>
  </nav>