resource/views/server_views.py
from flask import Blueprint, url_for, render_template, flash, request
from werkzeug.utils import redirect
from resource import db
from resource.models import Region, Server
from resource.forms import ServerForm

bp = Blueprint('server', __name__, url_prefix='/server')


@bp.route('create/region<int:region_id>/', methods=('GET', 'POST'))
def create(region_id):
    form = ServerForm()
    region = Region.query.get_or_404(region_id)

    if request.method == 'POST' and form.validate_on_submit():
        server = Server(region_id=region_id, host=form.host.data, cpu=form.cpu.data,
                        memory=form.memory.data, storage=form.storage.data)
        db.session.add(server)
        db.session.commit()
        return redirect(url_for('region.detail', region_id=region_id))

    return render_template('server/add_server.html', region=region, form=form)


@bp.route('update/<int:server_id>/', methods=('GET', 'POST'))
def update(server_id):
    form = ServerForm()
    server = Server.query.get_or_404(server_id)
    region_id = server.region_id

    if request.method == 'POST' and form.validate_on_submit():
        server.host = form.host.data
        server.cpu = form.cpu.data
        server.memory = form.memory.data
        server.storage = form.storage.data
        db.session.commit()
        return redirect(url_for('region.detail', region_id=region_id))

    return render_template('server/update_server.html', server=server, form=form)


@bp.route('delete/<int:server_id>/', methods=('GET', 'POST'))
def delete(server_id):
    server = Server.query.get_or_404(server_id)
    region_id = server.region_id

    if server:
        db.session.delete(server)
        db.session.commit()
    else:
        flash('server does not exist!')

    return redirect(url_for('region.detail', region_id=region_id))

resource/templates/server/add_server.html
{% extends "base.html" %}

{% block title %}
create server
{% endblock %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Add Server for {{ region.name }}</h5>
    <form method="post" class="my-3">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="host" class="col-form-label">Host</label>
            <input type="text" class="form-control" name="host" id="host">
        </div>
        <div class="mb-3">
            <label for="cpu" class="col-form-label">CPU</label>
            <input type="text" class="form-control" name="cpu" id="cpu">
        </div>
        <div class="mb-3">
            <label for="memory" class="col-form-label">Memory</label>
            <input type="text" class="form-control" name="memory" id="memory">
        </div>
        <div class="mb-3">
            <label for="storage" class="col-form-label">Storage</label>
            <input type="text" class="form-control" name="storage" id="storage">
        </div>
        <button type="submit" class="btn btn-primary">Confirm</button>
    </form>
</div>
{% endblock %}

resource/templates/server/delete_server.html
<style>
    .modal-content {
        background-color:dimgrey
    }
</style>

<div class="modal fade" id="modal_delete_server-{{ server.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete {{ server.host }}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Are you sure to delete {{ server.host }}?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <a class="btn btn-outline-danger" href="{{ url_for('server.delete', server_id=server.id) }}" role="button">Delete</a>
        </div>
      </div>
    </div>
  </div>

resource/templates/server/update_server.html
{% extends "base.html" %}

{% block title %}
{{ server.host }}
{% endblock %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Update {{ server.host }}</h5>
    <form method="post" class="my-3">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="host" class="col-form-label">Host</label>
            <input type="text" class="form-control" name="host" id="host" value="{{ server.host }}">
        </div>
        <div class="mb-3">
            <label for="cpu" class="col-form-label">CPU</label>
            <input type="text" class="form-control" name="cpu" id="cpu" value="{{ server.cpu }}">
        </div>
        <div class="mb-3">
            <label for="memory" class="col-form-label">Memory</label>
            <input type="text" class="form-control" name="memory" id="memory" value="{{ server.memory }}">
        </div>
        <div class="mb-3">
            <label for="storage" class="col-form-label">Storage</label>
            <input type="text" class="form-control" name="storage" id="storage" value="{{ server.storage }}">
        </div>
        <button type="submit" class="btn btn-primary">Confirm</button>
    </form>
</div>
{% endblock %}